### ISSUE TITLE
[question] cat inner puzzle

### ISSUE THREAD

**Issue by forReason** [Chia-Network/CAT-admin-tool#28]
I am currently investigating the creation of cats and would like to write my own inner puzzle.
I have seen the [cat_v2.clsp](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/puzzles/cat_v2.clsp) and noticed that it requires a INNER_PUZZLE to curry in. I cannot find a inner puzzle reference anywhere though. Neither in the documentation, the chia github repo nor in this repo.

I would like to ask how this is handled and if you have a reference for the default inner_puzzle as a starting point

**Comment by forReason** [comment]
some update, is it correct, the inner puzzle is hardcoded here?
```
 # Construct the intermediate puzzle
    p2_puzzle = Program.to(
        (1, [[51, 0, -113, curried_tail, solution], [51, address, amount, [address]]])
    )

    # Wrap the intermediate puzzle in a CAT wrapper
    cat_puzzle = construct_cat_puzzle(CAT_MOD, curried_tail.get_tree_hash(), p2_puzzle)
    cat_ph = cat_puzzle.get_tree_hash()
```

**Comment by Quexington** [comment]
Yes that is the inner puzzle that this repo uses for minting.  It's not a very effective inner puzzle for other purposes though. See here for more https://docs.chia.net/guides/chialisp-inner-puzzles?_highlight=inner&_highlight=puzzle
