### ISSUE TITLE
Dependency Mismatch with Chia Dev Tools

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/CAT-admin-tool#36]
We have mismatched dependencies between the cat admin tool (requires chia v2.1) and chia dev tools (requires chia v2.0).
This in addition to mismatched install instructions between the docs and github repo make it very confusing to follow the guide and examples.

What needs to be done:
- Update chia dev tools dependencies to align with cat admin tool (https://github.com/Chia-Network/chia-dev-tools/blob/main/setup.py#L16)
- Update github instructions to include the installation of cdv tools and pytest (pip install chia-dev-tools --no-deps & pip install pytest)
- Update the linux doc instructions to include the installation of cdv tools and pytest (pip install chia-dev-tools --no-deps & pip install pytest)

I am able to perform updates 2 and 3 but figure someone from engineering might want to make update number 1 so tests can be performed properly

**Comment by emlowe** [comment]
Resolved - all current for chia-blockchain 2.3.0
