### ISSUE TITLE
cant install CAT-admin-tool

### ISSUE THREAD

**Issue by subved** [Chia-Network/CAT-admin-tool#5]
ERROR: Could not find a version that satisfies the requirement clvm-rs==0.1.15 (from chia-blockchain) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.14, 0.1.16)
ERROR: No matching distribution found for clvm-rs==0.1.15

**Comment by Quexington** [comment]
Are you using a 32 bit operating system?  I'm pretty sure this only works on 64 bit.
